[book]
authors = ["Daniel Lozano"]
language = "en"
multilingual = false
src = "./"
title = "Alliance Business Suite Documentation"
description = "The Ultimate Business Development Platform"

[output.html.search]
enable = true

[output.html.fold]
enable = true
level = 0